export interface ICircularSliderProps {
    label: string ;
    width: number ;
    direction: number ;
    min: number ;
    max: number ;
    knobColor: string ;
    knobSize: number ;
    knobPosition: string ;
    knobOffset: number ;
    labelColor: string ;
    labelBottom: boolean ;
    labelFontSize: string ;
    valueFontSize: string ;
    appendToValue: string ;
    prependToValue: string ;
    verticalOffset: string ;
    hideLabelValue: boolean ;
    hideKnob: boolean ;
    knobDraggable: boolean ;
    progressColorFrom: string ;
    progressColorTo: string ;
    progressSize: number ;
    trackColor: string ;
    trackSize: number ;
    data: never[] ;
    dataIndex: number ;
    progressLineCap: string ;
    renderLabelValue: null ;
    children: JSX.Element | null ;
    onChange: ((value: any) => void) ;
    lockDashOffset: number | undefined ;
}
